main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('savekegiatan/', views.savekegiatan, name='savekegiatan'),
    path('savepeserta/<int:pk>', views.savepeserta, name='savepeserta'),
]

story6/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    name = models.CharField(max_length=125, default='none')

class Peserta(models.Model):
    #aktivitas = models.ForeignKey(Kegiatan, on_delete = models.CASCADE)
    name = models.CharField(max_length=125, default='none')
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.DO_NOTHING, default='none', null=True, blank=True)

    class Meta:
        ordering = ['name']

story6/forms.py
from django import forms
from .models import Kegiatan, Peserta
# from django.core.exceptions import ValidationError 
# from django.utils.translation import ugettext_lazy as _

class Input_Form(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields = ['name']
    error_messages = {
        'required' : 'please type'
    }
    name_attrs = {
        'type' : 'text',
        'placeholder' : 'kegiatan'
    }


    name = forms.CharField(label='kegiatan:', required=True, max_length=125, widget=forms.TextInput(attrs=name_attrs))

class Peserta_Form(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = ['name']
    error_messages = {
        'required' : 'please type'
    }
    name_attrs = {
        'type' : 'text',
        'placeholder' : 'nama'
    }


    name = forms.CharField(label='', required=True, max_length=125, widget=forms.TextInput(attrs=name_attrs))

story6/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Kegiatan, Peserta
from .forms import Input_Form, Peserta_Form
from django.urls import reverse

# Create your views here.
def kegiatan(request):
    kegiatan = Kegiatan.objects.all()
    peserta = Peserta.objects.all()
    response = {'kegiatan' : kegiatan, 'peserta' : peserta, 'input_form' : Input_Form, 'peserta_form' : Peserta_Form}
    return render(request, 'story6/kegiatan.html', response)


def savekegiatan(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        new_kegiatan = Kegiatan(name=form.cleaned_data['name'])
        new_kegiatan.save()
        return HttpResponseRedirect('/story6/kegiatan/')
    else:
        form = Input_Form() 
        return render(request,'story6/kegiatan.html')

def savepeserta(request, pk):
    form = Peserta_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        kegiatan_in = get_object_or_404(Kegiatan, pk=pk)
        new_peserta = Peserta()
        new_peserta.name = form.cleaned_data['name']
        new_peserta.kegiatan = kegiatan_in
        new_peserta.save()
        return HttpResponseRedirect('/story6/kegiatan/')
    else:
        form = Peserta_Form()
        return render(request,'story6/kegiatan.html')

story6/templates/story6/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story 6</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 align-self-center">
            <h1 class="h top-p"><mark id="mark">Kegiatan Ku </mark></h1>
        </div>
        <div class="col-sm-12">
            <form action="{% url 'story6:savekegiatan' %}" method="POST">
                {% csrf_token %}
               <h3>{{ input_form.as_p}} </h3> 
                <input class="submit btn" type="submit" value="Submit">
            </form>
            
        </div>
        <div class="col-sm-12">
            {% if kegiatan %}
            <table class="table table-borderless"> 
                {% for kg in kegiatan %}
                <tr>
                    <td>{{ kg.name }}</td>
                    <td>
                        <ul>
                            {% for pr in kg.peserta_set.all %}
                            <li>
                                {{ pr.name }}
                            </li>
                            {% endfor %}
                        </ul>
                        <form action="{% url 'story6:savepeserta' pk=kg.id %}" method="POST">
                            {% csrf_token %}
                            {{ peserta_form.as_p }}
                            <button class="submit btn" type="submit">Tambah peserta</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}