main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('matakuliah/', views.matakuliah, name='matakuliah'),
    path('savematakuliah/', views.savematakuliah, name='savematakuliah'),
    path('matakuliah/<int:pk>/', views.getmatkul, name='getmatkul'),
    path('matakuliah/<int:pk>/removematkul', views.removematkul, name='removematkul'),

]

story5/models.py
from django.db import models
#import uuid

# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length = 200)
    lecturer = models.CharField(max_length = 300)
    sks = models.IntegerField()
    description = models.TextField()
    year = models.CharField(max_length = 100)
    room = models.CharField(max_length = 100, default='none')

story5/forms.py
from django import forms
from .models import Course
from django.core.exceptions import ValidationError 
from django.utils.translation import ugettext_lazy as _

class Input_Form(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'lecturer', 'sks', 'description', 'year', 'room']
    error_messages = {
        'required' : 'please type'
    }
    name_attrs = {
        'type' : 'text',
        'placeholder' : 'nama mata kuliah'
    }
    lecturer_attrs = {
        'type' : 'text',
        'placeholder' : 'nama dosen'
    }
    sks_attrs = {
        'type' : 'number',
        'placeholder' : 'sks'
    }
    description_attrs = {
        'type' : 'text',
        'placeholder' : 'deskripsi mata kuliah'
    }
    year_attrs = {
        'type' : 'text',
        'placeholder' : 'semester tahun'
    }
    room_attrs = {
        'type' : 'text',
        'placeholder' : 'ruangan'
    }

    name = forms.CharField(label='Mata Kuliah:', required=True, max_length=200, widget=forms.TextInput(attrs=name_attrs))
    lecturer = forms.CharField(label='Dosen', required=True, max_length=300, widget=forms.TextInput(attrs=lecturer_attrs))
    sks = forms.IntegerField(label='Jumlah SKS', required=True, widget=forms.TextInput(attrs=sks_attrs))
    description = forms.CharField(label='Deskripsi', required=False, widget=forms.Textarea(attrs=description_attrs))
    year = forms.CharField(label='Tahun Ajaran', required=True, max_length=100, widget=forms.TextInput(attrs=year_attrs))
    room = forms.CharField(label='Ruang', required=True, max_length=100, widget=forms.TextInput(attrs=room_attrs))

    def clean_sks(self):
        data = self.cleaned_data['sks']
        if data < 1:
            raise ValidationError(_('SKS tidak boleh 0 atau negatif'))
        if data > 24:
            raise ValidationError(_('SKS melebihi batas maksimum'))
        return data

story5/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Course
from .forms import Input_Form
from django.urls import reverse

# Create your views here.
def matakuliah(request):
    courses = Course.objects.all()
    response = {'courses' : courses, 'input_form' : Input_Form}
    return render(request, 'story5/courses.html', response)


def savematakuliah(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect(reverse('story5:matakuliah'))
    else:
        form = Input_Form()
        validate = {'validate' : 'SKS berentang 1 - 24', 'input_form':form}  
        return render(request,'story5/courses.html', validate)

def getmatkul(request, pk):
    course_instance = get_object_or_404(Course, pk=pk)
    response = {'course_instance' : course_instance}
    return render(request, 'story5/getmatkul.html', response)

def removematkul(request, pk):
    course_instance = get_object_or_404(Course, pk=pk)
    response = {'course_instance' : course_instance}
    if request.method== "POST":
        course_instance.delete()
        return render(request, 'story5/removematkul.html', response)

story5/templates/story5/courses.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story 3</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 align-self-center">
            <h1 class="h top-p"><mark id="mark">Mata Kuliah</mark></h1>
        </div>
        <div class="col-sm-12">
            <p>{{ validate }}</p>
            <form action="{% url 'story5:savematakuliah' %}" method="POST">
                {% csrf_token %}
                <table class="table-responsive">
                    {{ input_form.as_table}}
                </table>
                <input class="submit btn" type="submit" value="Submit">
            </form>
            
        </div>
        <div class="col-sm-12">
            {% if courses %}
            <table class="table table-borderless"> 
                {% for course in courses %}
                <tr>
                    <td><a href="{{ course.id }}">{{ course.name }}</a></td>
                    <td>
                        <form action="{% url 'story5:removematkul' pk=course.id %}" method="POST">
                            {% csrf_token %}
                            <button class="submit btn" type="submit">Delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

story5/templates/story5/getmatkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story 3</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 align-self-center">
            <h1 class="h top-p"><mark id="mark">List Mata Kuliah</mark></h1>
        </div>
        <div class="col-sm-12">
            {% if course_instance %}
                <p>Nama Mata kuliah: {{ course_instance.name }}</p>
                <p>SKS: {{ course_instance.sks }}</p>
                <p>Tahun Ajaran: {{ course_instance.year }}</p>
                <p>Ruangan: {{ course_instance.room }}</p>
                <p>Deskripsi Mata kuliah:</p>
                <p>{{ course_instance.description }}</p>
                <p>Dosen Pengajar: {{ course_instance.lecturer }}</p>
        </div>
        <div class="col-sm-12">
            <form action="{% url 'story5:removematkul' pk=course_instance.id %}" method="POST">
                {% csrf_token %}
                <button class="submit btn" type="submit">Delete</button>
              </form>
        </div>
        {% endif %}
    </div>
</div>

{% endblock content %}

story5/templates/story5/removematkul.html
<!--kalo bika per matkul ada pilihan delete this matkul -->
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>story 3</title>
{% endblock meta %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-12 align-self-center">
            <h1 class="h top-p"><mark id="mark">Mata Kuliah</mark></h1>
        </div>
        <div class="col-sm-12">
            {% if course_instance %}
                <p>Berhasil menghapus {{ course_instance.name }}</p>
            {% endif %}

            <a id = "a" class="btn" href="{% url 'story5:matakuliah' %}" role="button">Kembali</a>
        </div>
    </div>
</div>

{% endblock content %}