main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

ppwstory/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story3/', include('story3.urls')),
    path('story5/', include('story5.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

story3/urls.py
from django.urls import path
from . import views

app_name = 'story3'

urlpatterns = [
    path('expirience/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
]

story5/urls.py
from django.urls import path
from . import views

app_name = 'story5'

urlpatterns = [
    path('matakuliah/', views.matakuliah, name='matakuliah'),
    path('savematakuliah/', views.savematakuliah, name='savematakuliah'),
    path('matakuliah/<int:pk>/', views.getmatkul, name='getmatkul'),
    path('matakuliah/<int:pk>/removematkul', views.removematkul, name='removematkul'),

]

story6/urls.py
from django.urls import path
from . import views

app_name = 'story6'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
    path('savekegiatan/', views.savekegiatan, name='savekegiatan'),
    path('savepeserta/<int:pk>', views.savepeserta, name='savepeserta'),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.index, name='index'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-dark"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto"> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'main:home' %}">Home</a>
          </li> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story3:profile' %}">Profile</a>
          </li> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story3:contact' %}">Contact</a>
          </li> 
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story5:matakuliah' %}">Mata Kuliah</a>
          </li>
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan</a>
          </li>
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story7:index' %}">Story 7</a>
          </li>
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'story8:index' %}">Books</a>
          </li>
          
          {% if not user.is_authenticated %}
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a id = "a" class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %}
      </ul> 
    </div>
</nav>

{% block content %}
{% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  
<script src="{% static 'js/jquery-3.5.1.js' %}"></script>
{% block script %}
{% endblock script %}

</body>
</html>

templates/footer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'css/fontawesome/css/all.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}

</head>
<body>


      <nav class="footer navbar navbar-expand-sm navbar-dark"> 
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto"> 
              <li class="nav-item"> 
                <a id = "a" class="round-btn btn" href="https://www.instagram.com/syifarizka/" target="_blank"><i id = "iconsfa" class="fab fa-instagram"></i></a>
              </li> 
              <li class="nav-item"> 
                <a id = "a" class="round-btn btn" href="https://www.linkedin.com/in/syifa-rizka-sagita/" target="_blank"><i id = "iconsfa" class="fab fa-linkedin-in"></i></a>
              </li>
          </ul> 
        </div>
    </nav>

</body>
</html>